name:    ted2srt
version: "3.20200412"

dependencies:

# Due to a bug in GHC 8.0.1, we block its usage
# See: https://ghc.haskell.org/trac/ghc/ticket/12130
- base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5

- aeson
- base64-bytestring
- bytestring
- conduit
- conduit-extra
- containers
- cryptonite
- cryptonite-conduit
- directory
- either
- hedis
- html-conduit
- http-conduit
- http-types
- load-env
- lucid
- memory
- monad-logger
- mtl
- network
- persistent
- persistent-postgresql
- persistent-template
- raw-strings-qq
- regex-posix
- rio
- servant-lucid
- servant-server
- system-filepath
- text
- time
- transformers
- unordered-containers
- vector
- wai
- xml-conduit

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  default-extensions:
  - DataKinds
  - DeriveGeneric
  - FlexibleInstances
  - LambdaCase
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - QuasiQuotes
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TypeFamilies
  ghc-options:
  - -Wall
  - -fwarn-tabs

# Runnable executable for our application
executables:
  fetch:
    main: fetch.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ted2srt

  ted2srt:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ted2srt
    - warp
    - wai-extra

# Test suite
# tests:
#   test:
#     main: Main.hs
#     source-dirs: test
#     default-extensions:
#     - NoImplicitPrelude
#     - OverloadedStrings
#     ghc-options: -Wall
#     dependencies:
#     - ted2srt
#     - hspec >=2.0.0
#     - process
